/**
 * AXP192_reg.h - Register aliases of AXP192
 * 
 * Human-readable names (as readable as they can be) for AXP192 registers.
 * 
 * (C) 2019 - Pablo Bacho <pablo@fabricadigital.org>
 * This code is licensed under the MIT License.
 */

#ifndef _AXP192_REG_H_
#define _AXP192_REG_H_

// Group 1: Basic power control
#define INPUT_POWER_STATUS_REG 0x00
#define MODE_POWER_CHARGE_STATUS_REG 0x01
#define OTG_VBUS_STATUS_REG 0x04
#define DATA_BUFFER_0_REG 0x06
#define DATA_BUFFER_1_REG 0x07
#define DATA_BUFFER_2_REG 0x08
#define DATA_BUFFER_3_REG 0x09
#define DATA_BUFFER_4_REG 0x0A
#define DATA_BUFFER_5_REG 0x0B
#define EXTEN_DCDC2_SWITCH_CONTROL_REG 0x10
#define DCDC1_DCDC3_LDO2_LDO3_SWITCH_CONTROL_REG 0x12
#define DCDC2_VOLTAGE_SETTING_REG 0x23
#define DCDC2_VOLTAGE_SLOPE_SETTING_REG 0x25
#define DCDC1_VOLTAGE_SETTING_REG 0x26
#define DCDC3_VOLTAGE_SETTING_REG 0x27
#define LDO2_LDO3_VOLTAGE_SETTING_REG 0x28
#define VBUS_IPSOUT_PATH_SETTING_REG 0x30
#define VOFF_SHUTDOWN_VOLTAGE_SETTING_REG 0x31
#define OFF_BATTERY_DETECTION_CHGLED_CONTROL_REG 0x32
#define CHARGE_CONTROL_1_REG 0x33
#define CHARGE_CONTROL_2_REG 0x34
#define BACKUP_BATTERY_CHARGING_CONTROL_REG 0x35
#define PEK_SETTING_REG 0x36
#define DCDC_CONVERTER_OPERATING_FREQUENCY_REG 0x37
#define LOW_BATTERY_CHARGE_WARNING_REG 0x38
#define BATTERY_CHARGING_HIGH_TEMPERATURE_ALARM_REG 0x39
#define APS_LOW_LEVEL_1_REG 0x3A
#define APS_LOW_LEVEL_2_REG 0x3B
#define LOW_BATTERY_DISCHARGE_ALARM_REG 0x3C
#define BATTERY_DISCHARGE_HIGH_TEMPERATURE_ALARM_REG 0x3D
#define DCDC_OPERATION_MODE_REG 0x80
#define ADC_ENABLE_1_REG 0x82
#define ADC_ENABLE_2_REG 0x83
#define ADC_SAMPLE_RATE_TS_PIN_CONTROL_REG 0x84
#define GPIO_INPUT_RANGE_REG 0x85
#define GPIO1_ADC_IRQ_RISING_THRESHOLD_REG 0x86
#define GPIO1_ADC_IRQ_FALLING_THRESHOLD_REG 0x87
#define TIMER_CONTROL_REG 0x8A
#define VBUS_MONITORING_REG 0x8B
#define OVERTEMPERATURE_SHUTDOWN_CONTROL_REG 0x8F

// Group 2: GPIO Control
#define GPIO0_CONTROL_REG 0x90
#define GPIO0_LDO_MODE_OUTPUT_VOLTAGE_REG 0x91 // ???
#define GPIO1_CONTROL_REG 0x92
#define GPIO2_CONTROL_REG 0x93
#define GPIO_2_0_SIGNAL_STATUS_REG 0x94
#define GPIO_4_3_FUNCTION_CONTROL_REG 0x95
#define GPIO_4_3_SIGNAL_STATUS_REG 0x96
#define GPIO_2_0_PULLDOWN_CONTROL_REG 0x97
#define PWM1_FREQUENCY_REG 0x98
#define PWM1_DUTY_CYCLE_1_REG 0x99
#define PWM1_DUTY_CYCLE_2_REG 0x9A
#define PWM2_FREQUENCY_REG 0x9B
#define PWM2_DUTY_CYCLE_1_REG 0x9C
#define PWM2_DUTY_CYCLE_2_REG 0x9D
#define N_RSTO_GPIO5_CONTROL_REG 0x9E

// Group 3: Interrupt control
#define IRQ_ENABLE_CONTROL_1_REG 0x40
#define IRQ_ENABLE_CONTROL_2_REG 0x41
#define IRQ_ENABLE_CONTROL_3_REG 0x42
#define IRQ_ENABLE_CONTROL_4_REG 0x43
#define IRQ_ENABLE_CONTROL_5_REG 0x4A
#define IRQ_STATUS_1_REG 0x44
#define IRQ_STATUS_2_REG 0x45
#define IRQ_STATUS_3_REG 0x46
#define IRQ_STATUS_4_REG 0x47
#define IRQ_STATUS_5_REG 0x4D

// Group 4: ADC
#define ACIN_VOLTAGE_ADC_DATA_HIGH_REG 0x56
#define ACIN_VOLTAGE_ADC_DATA_LOW_REG 0x57 // ???
#define ACIN_CURRENT_ADC_DATA_HIGH_REG 0x58
#define ACIN_CURRENT_ADC_DATA_LOW_REG 0x59
#define VBUS_VOLTAGE_ADC_DATA_HIGH_REG 0x5A
#define VBUS_VOLTAGE_ADC_DATA_LOW_REG 0x5B
#define VBUS_CURRENT_ADC_DATA_HIGH_REG 0x5C
#define VBUS_CURRENT_ADC_DATA_LOW_REG 0x5D
#define INTERNAL_TEMPERATURE_ADC_DATA_HIGH_REG 0x5E
#define INTERNAL_TEMPERATURE_ADC_DATA_LOW_REG 0x5F
#define TS_ADC_DATA_HIGH = 0x62
#define TS_ADC_DATA_LOW = 0x63
#define GPIO0_VOLTAGE_ADC_DATA_HIGH = 0x64
#define GPIO0_VOLTAGE_ADC_DATA_LOW = 0x65
#define GPIO1_VOLTAGE_ADC_DATA_HIGH = 0x66
#define GPIO1_VOLTAGE_ADC_DATA_LOW = 0x67
#define GPIO2_VOLTAGE_ADC_DATA_HIGH = 0x68
#define GPIO2_VOLTAGE_ADC_DATA_LOW = 0x69
#define GPIO3_VOLTAGE_ADC_DATA_HIGH = 0x6A
#define GPIO3_VOLTAGE_ADC_DATA_LOW = 0x6B
// Todo: 0x70 to 0x7F

#define BATTERY_CHARGING_COULOMB_COUNTER_DATA_31_24_REG 0xB0
#define BATTERY_CHARGING_COULOMB_COUNTER_DATA_23_16_REG 0xB1
#define BATTERY_CHARGING_COULOMB_COUNTER_DATA_15_8_REG 0xB2
#define BATTERY_CHARGING_COULOMB_COUNTER_DATA_7_0_REG 0xB3
#define BATTERY_DISCHARGE_COULOMB_COUNTER_DATA_31_24_REG 0xB4
#define BATTERY_DISCHARGE_COULOMB_COUNTER_DATA_23_16_REG 0xB5
#define BATTERY_DISCHARGE_COULOMB_COUNTER_DATA_15_8_REG 0xB6
#define BATTERY_DISCHARGE_COULOMB_COUNTER_DATA_7_0_REG 0xB7
#define COULOMB_COUNTER_CONTROL_REG 0xB8

#endif // _AXP192_REG_H_