

// Generated by utils/generate_c_pic.py

#ifndef BITMAPS_DEFINITIONS
#define BITMAPS_DEFINITIONS

#include "bitmaps.h"

extern bitmap_data bmp_db_0;
extern bitmap_data bmp_db_1;
extern bitmap_data bmp_db_2;
extern bitmap_data bmp_db_3;
extern bitmap_data bmp_db_4;
extern bitmap_data bmp_db_5;
extern bitmap_data bmp_db_6;
extern bitmap_data bmp_db_7;
extern bitmap_data bmp_db_8;
extern bitmap_data bmp_db_9;
extern bitmap_data bmp_db_10;


extern int n_bitmaps;
extern bitmap_data *bitmap_db[];

#endif

