
// Generated by utils/generate_c_pic.py

#ifndef BITMAPS_DEFINITIONS
#define BITMAPS_DEFINITIONS

#include "bitmaps.h"

bmp_grey_color_t bmp_db_palette[16];

extern bitmap_data bmp_db_0;
extern bitmap_data bmp_db_1;
extern bitmap_data bmp_db_2;
extern bitmap_data bmp_db_3;
extern bitmap_data bmp_db_4;
extern bitmap_data bmp_db_5;
extern bitmap_data bmp_db_6;
extern bitmap_data bmp_db_7;
extern bitmap_data bmp_db_8;
extern bitmap_data bmp_db_9;
extern bitmap_data bmp_db_10;
extern bitmap_data bmp_db_11;
extern bitmap_data bmp_db_12;
extern bitmap_data bmp_db_13;
extern bitmap_data bmp_db_14;
extern bitmap_data bmp_db_15;
extern bitmap_data bmp_db_16;
extern bitmap_data bmp_db_17;
extern bitmap_data bmp_db_18;
extern bitmap_data bmp_db_19;
extern bitmap_data bmp_db_20;
extern bitmap_data bmp_db_21;
extern bitmap_data bmp_db_22;
extern bitmap_data bmp_db_23;
extern bitmap_data bmp_db_24;
extern bitmap_data bmp_db_25;
extern bitmap_data bmp_db_26;
extern bitmap_data bmp_db_27;
extern bitmap_data bmp_db_28;
extern bitmap_data bmp_db_29;
extern bitmap_data bmp_db_30;
extern bitmap_data bmp_db_31;
extern bitmap_data bmp_db_32;
extern bitmap_data bmp_db_33;
extern bitmap_data bmp_db_34;
extern bitmap_data bmp_db_35;
extern bitmap_data bmp_db_36;
extern bitmap_data bmp_db_37;
extern bitmap_data bmp_db_38;


extern int n_bitmaps;
extern bitmap_data *bitmap_db[];

#endif
