
// Generated by utils/generate_c_pic.py

#ifndef BITMAPS_DEFINITIONS
#define BITMAPS_DEFINITIONS

#include "bitmaps.h"

extern bitmap_data bmp_db_0_NORMAL_FONT_SIZE;
extern bitmap_data bmp_db_1_NORMAL_FONT_SIZE;
extern bitmap_data bmp_db_2_NORMAL_FONT_SIZE;
extern bitmap_data bmp_db_3_NORMAL_FONT_SIZE;
extern bitmap_data bmp_db_4_NORMAL_FONT_SIZE;
extern bitmap_data bmp_db_5_NORMAL_FONT_SIZE;
extern bitmap_data bmp_db_6_NORMAL_FONT_SIZE;
extern bitmap_data bmp_db_7_NORMAL_FONT_SIZE;
extern bitmap_data bmp_db_8_NORMAL_FONT_SIZE;
extern bitmap_data bmp_db_9_NORMAL_FONT_SIZE;
extern bitmap_data bmp_db_10_NORMAL_FONT_SIZE;
extern bitmap_data bmp_db_0_SMALL_FONT_SIZE;
extern bitmap_data bmp_db_1_SMALL_FONT_SIZE;
extern bitmap_data bmp_db_2_SMALL_FONT_SIZE;
extern bitmap_data bmp_db_3_SMALL_FONT_SIZE;
extern bitmap_data bmp_db_4_SMALL_FONT_SIZE;
extern bitmap_data bmp_db_5_SMALL_FONT_SIZE;
extern bitmap_data bmp_db_6_SMALL_FONT_SIZE;
extern bitmap_data bmp_db_7_SMALL_FONT_SIZE;
extern bitmap_data bmp_db_8_SMALL_FONT_SIZE;
extern bitmap_data bmp_db_9_SMALL_FONT_SIZE;
extern bitmap_data bmp_db_10_SMALL_FONT_SIZE;


extern int n_bitmaps;
extern bitmap_data *bitmap_db[];

#endif

